urls:
    - url: "http://wp.pl"
      delay: 60

    - url: "http://o2.pl"
      delay: 180

    - url: "http://pudelek.pl"
      delay: 75

    - url: "https://httpbin.org/status/500"
      delay: 75

